# Generated by Django 6.0.6 on 2026-06-09 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('AULA', 'Aula'), ('LABORATORIO', 'Laboratorio'), ('AUDITORIO', 'Auditorio')], max_length=20)),
                ('piso', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_problema', models.CharField(choices=[('PROYECTOR', 'Proyector'), ('COMPUTADORA', 'Computadora'), ('ILUMINACION', 'Iluminacion'), ('MOBILIARIO', 'Mobiliario'), ('CONECTIVIDAD', 'Conectividad'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('RESUELTA', 'Resuelta')], default='PENDIENTE', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.aula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ud', models.CharField(max_length=20, unique=True)),
                ('rol', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('ADMINISTRADOR', 'Administrador')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='incidencias.incidencia')),
            ],
        ),
    ]
