# Generated by Django 6.0.6 on 2026-06-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='piso',
            field=models.CharField(max_length=30),
        ),
    ]
