# Generated by Django 4.2.16 on 2026-06-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_alter_aula_id_alter_incidencia_id_alter_perfil_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='registro_ud',
            field=models.CharField(max_length=20),
        ),
    ]
